# Generated by Django 4.2.3 on 2023-07-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('topic', models.CharField(default='placeholder', max_length=255, null=True)),
                ('message', models.TextField(default='', null=True)),
                ('device_serial', models.CharField(default='placeholder', max_length=10240, null=True)),
            ],
        ),
    ]
