# Generated by Django 4.2.3 on 2023-07-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.IntegerField()),
                ('interval', models.IntegerField()),
                ('fullAlarmLimit', models.IntegerField()),
                ('version', models.CharField(max_length=10)),
                ('deltaTemp', models.IntegerField()),
                ('deltaTime', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('deviceStatusCheckTime', models.IntegerField()),
                ('depth', models.IntegerField()),
                ('fullness', models.IntegerField()),
                ('toleranceValue', models.IntegerField()),
                ('sensorWakeUp', models.IntegerField()),
            ],
        ),
    ]
