# Generated by Django 4.2.3 on 2023-07-20 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0002_device'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.RemoveField(
            model_name='device',
            name='deltaTemp',
        ),
        migrations.RemoveField(
            model_name='device',
            name='deltaTime',
        ),
        migrations.RemoveField(
            model_name='device',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='device',
            name='deviceStatusCheckTime',
        ),
        migrations.RemoveField(
            model_name='device',
            name='fullAlarmLimit',
        ),
        migrations.RemoveField(
            model_name='device',
            name='fullness',
        ),
        migrations.RemoveField(
            model_name='device',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='device',
            name='sensorWakeUp',
        ),
        migrations.RemoveField(
            model_name='device',
            name='status',
        ),
        migrations.RemoveField(
            model_name='device',
            name='toleranceValue',
        ),
        migrations.RemoveField(
            model_name='device',
            name='ts',
        ),
        migrations.RemoveField(
            model_name='device',
            name='version',
        ),
        migrations.AddField(
            model_name='device',
            name='device_serial',
            field=models.CharField(default='placeholder', max_length=10240, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='message',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='topic',
            field=models.CharField(default='placeholder', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
